### ISSUE TITLE
Um playbook para configurar inicialmente o servidor web

### ISSUE THREAD

**Issue by gomex** [DadosAbertosDeFeira/iac#1]
Esse [playbook](https://github.com/DadosAbertosDeFeira/iac/blob/main/playbook.yml) não deverá aplicar nenhuma task especifica, apenas uso do roles baixadas via [requirements.yml](https://github.com/DadosAbertosDeFeira/iac/blob/main/requirements.yml).

O que deve ser feito nessa task:

- [x] Instalar docker + dokku
- [x] Criar aplicação dokku
- [x] Instalar plugins do dokku (Let's encrypt e clone)
- [x] Configurar let's encrypt na aplicação criada
- [x] Configurar a aplicação pra receber chamada http via nginx do Dokku
- [x] Criar usuários e colocar as chaves públicas
- [x] Mudar a senha de root e apagar usuários desnecessários

Siga o README e execute o teste. Ele deve passar para essa issue ser completada.

Obs: A distro usada será ubuntu 18.04 LTS.

Critérios para aceitação dessa role:

- [ ] Ambiente recebendo requisição HTTPS com certificado válido

PS: Preciso criar um teste automatizado para validar que tem certificado válido (ver como fazer com let's encrypt de teste)

Documentação do Dokku: http://dokku.viewdocs.io/dokku/getting-started/installation/ 
Código ansible oficial do Dokku: https://github.com/dokku/ansible-dokku

PS: Estamos abertos a usar outra solução (de PaaS ou não), mas precisar ser algo simples como Dokku.

**Comment by gomex** [comment]
O playbook.yml que temos hoje já utiliza uma role que faz basicamente tudo na instalação e configuração do Docker e Dokku. Ele também ja cria a aplicação, mas não configura o SSL/let's encrypt. 

Existem comandos no dokku que fazem isso, mas estou ainda um pouco desconfortável de usar command ou shell no ansible pra executar esse comandos. Seria muito bom achar uma forma via ansible de configurar isso, sem precisar dar comandos, mas se for usar comandos eu queria que fosse idempotente. Isso quer dizer que se eu executar o mesmo ansible duas vezes eu quero que na segunda o ansible fale que ta ok, ao invés de changed ou failed.

A configuração de usuários eu acho que precisamos de uma forma mais dinâmica de listar usuários, ou podemos apenas adotar a que foi sugerida no ansible oficial do dokku.

Segue um bom documento pra revisar seu código ansible: https://www.ansible.com/blog/ansible-best-practices-essentials

Obs: Se encontrar erro no código atual com base nas melhores práticas, podem reportar ;) Todo mundo erra ;)

**Comment by selmison** [comment]
Olá, @gomex,

Na documentação em https://github.com/dokku/dokku-letsencrypt diz que :`Your app must already be deployed and accessible over the internet (i.e. in the browser) in order to add letsencrypt to your app.`

Pelo que entendi o certificado SSL só será gerado pelo Letsencrypt quando a apliação foi deployada e já está acessível pela internet. Entendo, então, que o SSL deve ser o último passo. Estou correto?

**Comment by selmison** [comment]
Olá, @gomex,

O objetivo desse servidor é subir o backend contido em https://github.com/DadosAbertosDeFeira/maria-quiteria, confere?

Nesse repositório, notei que o aplicativo está usando o docker-compose e me parece que dokku não trabalha com docker-compose. Há um motivo especial para se adotado o Dokku?

Como a Issue informou que pode-se utilizar uma outra solução diferente do Dokku, pode ser que tente adotar outra opção, tudo bem?

**Comment by gomex** [comment]
> Há um motivo especial para se adotado o Dokku?

O motivo é o fato do Dokku facilitar o processo de deploy. Ele é um PaaS. Usaremos docker-compose, se precisar, mas para apps prontas que não tenham suporte a plugin do Dokku ;)

**Comment by selmison** [comment]
> O motivo é o fato do Dokku facilitar o processo de deploy. Ele é um PaaS. Usaremos docker-compose, se precisar, mas para apps prontas que não tenham suporte a plugin do Dokku ;)

Então, a ideia é ter todas as imagens Docker do backend em um registry e o Dokku terá o papel de deployar e linkar corretamente esses containers?

Se esse for o caso, em que registry as imagens podem ser publicadas?

**Comment by gomex** [comment]
A ideia é que a app principal, mariaquiteria, essa seria buildada pelo Dokku, não precisa de registry nesse caso.

**Comment by selmison** [comment]
> A ideia é que a app principal, mariaquiteria, essa seria buildada pelo Dokku, não precisa de registry nesse caso.

Continuando a minha seção faqs rs.

Reforçando o meu entendimento: a ideia é subir o app princicipal (web) via buildpack do Dokku.

Enquanto que os serviços auxiliares, como o postgres, tika, rabbitmq e dramatiq, se não forem compatíveis com o Dokku, usaremos outra alternativa, talvez o docker. Correto?

**Comment by gomex** [comment]
Não precisamos mais do let's encrypt, o LB do provedor dar conta disso ;)
