### ISSUE TITLE
Construir imagem docker do TIKA

### ISSUE THREAD

**Issue by bemanuel** [DadosAbertosDeFeira/iac#11]
A imagem padrão do  [Apache Tika](https://hub.docker.com/r/apache/tika) - [Dockerfile](https://github.com/apache/tika-docker/blob/master/full/Dockerfile), não inclui o OCR para o Português.

O PR deve ser feito para esse repo: https://github.com/DadosAbertosDeFeira/iac-docker-tika

Por isso é necessário criar uma imagem docker contemplando as necessidades do projeto, seguindo os mesmos padrões da imagem oficial do grupo Apache, removendo as linguagens desnecessárias (ita, fra,...) e adicionando o português (por)

Critérios de aceitação:
 - [x] Seguir o modelo do Apache Tika
 - [x] A porta padrão é a 9998
 
O CI deve ter:
 - [x] Um lint do Dockerfile
 - [x] Um build da imagem
 - [x] Um teste simples qualquer pra validar a imagem ( ex.: saber se o serviço subiu e está escutando na porta )
 - [x] Trigger para que a partir de uma tag do github ele buidar com a tag igual a tag do github e depois fazer upload no hub.docker.com

**Comment by gomex** [comment]
Concluído! Obrigado @bemanuel
