### ISSUE TITLE
Colocar os dados seguros para deploy

### ISSUE THREAD

**Issue by gomex** [DadosAbertosDeFeira/iac#14]
Existem algumas variáveis seguras que precisam ser aplicadas na app dokku, mas elas não podem ser colocadas em texto plano no github. Elas precisam ser encriptadas.

Pretendemos usar ansible-vault pra isso.

**Comment by edsoncelio** [comment]
Algumas dúvidas sobre essa issue:

- Vendo o playbook, identifiquei como segredo as envs do ` dokku_users` e a `DJANGO_SECRET_KEY`, pode confirmar quais chaves variáveis devem ser encriptadas? (se são apenas essas ou mais alguma outra)

- Já pensando na solução, faria sentido criar um diretório para o arquivo `.yaml` com as variáveis encriptadas (via ansible-vault)e apenas incluir com o `include_vars` / `vars_files?` Ou sugere algo diferente?

**Comment by gomex** [comment]
As variáveis são:

```
DATABASE_URL
CLOUDAMQP_URL
CLOUDAMQP_APIKEY
DJANGO_SECRET_KEY
```
Obs: A chave de ssh_key é pública, de boa deixar aberta ;)

**Comment by marcelomansur** [comment]
Pessoal, tem alguém trabalhando nessa issue?
Acredito que precisaremos de um lugar para armazenar a senha do ansible vault, certo?
Gostaria de ajudar neste.

**Comment by gomex** [comment]
@marcelomansur parece que @edsoncelio tem um PR pra mandar, mas ainda não mandou ;)

O lugar para guardar pode ficar tranquilo que resolvo essa parte.

**Comment by ya-kimura** [comment]
contribuidores do PR @edsoncelio @marcelomansur @itsmael and me... hehehehe

**Comment by edsoncelio** [comment]
@gomex acho que podemos fechar essa issue :)

**Comment by gomex** [comment]
Valeu @edsoncelio
