### ISSUE TITLE
Proteger o nome e porta do servidor a ser feito deploy para evitar vazamento de dados

### ISSUE THREAD

**Issue by gomex** [DadosAbertosDeFeira/iac#18]
Hoje o deploy do mariaquiteria está exibindo essa mensagem no passo "Push to Dokku":

```
Generating SSH_HOST_KEY from ssh-keyscan against nat-25434.nuvem-brasil-10.absamcloud.com:43841
# nat-25434.nuvem-brasil-10.absamcloud.com:43841 SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
# nat-25434.nuvem-brasil-10.absamcloud.com:43841 SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
# nat-25434.nuvem-brasil-10.absamcloud.com:43841 SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
# nat-25434.nuvem-brasil-10.absamcloud.com:43841 SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
# nat-25434.nuvem-brasil-10.absamcloud.com:43841 SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
```

Isso é o nome do host dokku, com a porta. Eu sei que esconder esses dados não é o suficiente para oferecer uma real medida de segurança, afinal somente esconder é segurança por obscuridade, mas não sei se precisamos oferecer dados de "mão beijada para o atacante".

Precisamos criar um PR no repositório que é responsável por essa action: https://github.com/dokku/github-action

Nesse PR deve ter uma opção para ocultar o host e port, o default deve ser o comportamento padrão da action hoje, que é expor.

**Comment by felipefrizzo** [comment]
@gomex olhando a documentação acredito que seja melhor usarmos o output do `ssh-keyscan -t rsa -p PORT HOST` e atribuirmos para uma variável no secrets, essa variável substitui o comando de keyscan on de fly, e assim não teriamos mais o output na pipeline

* `ssh_host_key: The github-action will otherwise generate this on the fly via ssh-keyscan.`

Teriamos algo como isso aqui
```
...
with:
  branch: main
  ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
  git_remote_url: ${{ secrets.DOKKU_REMOTE_URL }}
  ssh_host_key: ${{ secrets.SSH_HOST_KEY }}
```

o que você acha ?

**Comment by gomex** [comment]
@felipefrizzo eu acho uma ótima, me manda um PR com isso?

**Comment by gomex** [comment]
Resolvido! Obrigado @felipefrizzo
