### ISSUE TITLE
Configurar check automático no deploy do dokku

### ISSUE THREAD

**Issue by gomex** [DadosAbertosDeFeira/iac#19]
Ao fazer deploy o dokku informa a seguinte mensagem:

```
Processing deployment checks
       No CHECKS file found. Simple container checks will be performed.
       For more efficient zero downtime deployments, create a CHECKS file. See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
```

O objetivo dessa issue é olhar a forma como o Dokku sugere que façamos o check e propor algo.

**Comment by ya-kimura** [comment]
Dando um check na issue aqui para ver nesta semana. Não consegui marcar o Edson aqui, mas como ele inspirou o interesse, ele está automaticamente nessa issue também. hahahaha

**Comment by KarlCF** [comment]
Gostaria de acompanhar, só não tenho a experiência ;(

**Comment by ya-kimura** [comment]
@KarlCF vamos entrar no discord hoje  lá pelas 20h no server da mentoria.

**Comment by edsoncelio** [comment]
Foi feita uma call sobre essa issue, alguns pontos levantados:

* A princípio, o check do Dokku espera apenas por um arquivo `CHECK` na raiz do projeto com uma instrução de checagem.
* Foi verificado que o projeto expõe um healthcheck no endpoind https://www.dadosabertosdefeira.com.br/api/ (a princípio pode ser usado)
* Sobre as instruções do arquivo `CHECK` ficamos de verificar como isso funciona, nos exemplos não ficou muito claro se podemos checar por um código http ou apenas por strings

Como atividade, ficamos de configurar uma instância do Dokku para testar a sintaxe e funcionamento com algo do tipo:
```
/api {"status": "available"}
```
Pessoas participantes da call: @ya-kimura @KarlCF @marcelomansur

**Comment by gomex** [comment]
O arquivo CHECK precisa ser criado no repositório do produto: https://github.com/DadosAbertosDeFeira/maria-quiteria

**Comment by edsoncelio** [comment]
Aberto PR relacionado a arquivo CHECKS, feito em 29/03.
Participantes: @ya-kimura @marcelomansur @KarlCF @GabrielSeiffert e @vilelf

**Comment by edsoncelio** [comment]
Atualizando status dessa atividade: 
* Verificado que o Django usa uma configuração para limitar os hosts de onde vai receber requisições, sendo definido pela variável `ALLOWED_HOSTS`;
* Até o momento, ainda não consegui identificar uma forma de fazer um "append" dos  hosts dinamicamente nessa variável após receber via variável de ambiente;

**Comment by anapaulagomes** [comment]
@edsoncelio se esse append for via código posso tentar te ajudar.

**Comment by edsoncelio** [comment]
@gomex o PR foi mergeado, quando puder, podemos fechar essa issue :)

**Comment by gomex** [comment]
Muito bom! Valeu @edsoncelio
