### ISSUE TITLE
O deploy do ansible precisa quebrar quando não tiver host disponível

### ISSUE THREAD

**Issue by gomex** [DadosAbertosDeFeira/iac#20]
Quando o ansible não tem conteúdo no arquivo hosts a execução do ansible não quebra o pipeline, mas tb não faz deploy em local algum. Precisamos pensar em alguma solução pra isso.

**Comment by gomex** [comment]
Segue um exemplo do erro que estou falando: https://github.com/DadosAbertosDeFeira/iac/runs/1731521563?check_suite_focus=true

```
ansible-playbook playbook.yml -i hosts -v
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.1/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.1/x64/lib
Using /home/runner/work/iac/iac/ansible.cfg as config file
Warning: : provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [all] *********************************************************************
skipping: no hosts matched

PLAY RECAP *********************************************************************

Wednesday 20 January 2021  00:05:15 +0000 (0:00:00.003)       0:00:00.003 ***** 
=============================================================================== 
```

**Comment by gomex** [comment]
Pra resolver, precisamos achar algo pra garantir que o CI falhe se não tiver contéudo.

**O melhor caminho**: É achar uma forma do comando ansible mesmo retornar código diferente de 0 em caso de não achar host e não apenas mandar essa mensagem "Warning: : provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'"

Se não tiver como o comando ansible retornar erro nesse caso, teremos que colocar uma checagem antes de executar o ansible pra validar se tem contéudo lá ou algum comando depois pra validar se a mensagem do warning não apareceu ou algo do tipo.

**Comment by gomex** [comment]
Link do arquivo do CI: https://github.com/DadosAbertosDeFeira/iac/blob/main/.github/workflows/ci.yml

**Comment by adell** [comment]
Tentando assumir esta.

**Comment by edsoncelio** [comment]
@gomex algo assim resolveria? nunca usei (apenas pesquei da doc haha): https://docs.ansible.com/ansible/latest/reference_appendices/config.html#inventory-any-unparsed-is-failed

Mas ao que vi é possível definir se o ansible vai tratar como um warning ou um erro :)

**Comment by edsoncelio** [comment]
@gomex validei aqui e a opção que corrige isso já está funcionando, só clonei o projeto e sem criar arquivo de inventário (`hosts`) o ansible dispara um _error_ ao invés de um _warning_:

``` (.venv) edsoncelio@ubuntu:~/Documents/iac$ ansible-playbook -i hosts playbook.yml   

[WARNING]: Unable to parse /home/edsoncelio/Documents/iac/hosts as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.
```
A opção para habilitar esse erro já está no `ansible.cfg`:
```
[inventory]
# Falha quando o parse do inventário não passar (Ansible 2.4+)
unparsed_is_failed=true
```

Se eu definir `unparsed_is_failed` para `false` temos o erro original:

```
[WARNING]: Unable to parse /home/edsoncelio/Documents/iac/hosts as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does
not match 'all'

PLAY [all] ****************************************************************************************************
skipping: no hosts matched

PLAY RECAP ****************************************************************************************************

Monday 15 February 2021  05:46:29 -0800 (0:00:00.003)       0:00:00.003 ******* 
```
Conseguimos testar isso no pipeline?

**Comment by gomex** [comment]
@edsoncelio é isso mesmo. Manda um PR pra mudar nosso ansible.cfg?

**Comment by edsoncelio** [comment]
Como sugeriu @gomex, rodei o CI no fork (com algumas alterações apenas para verificar se quebra caso o host não seja parseado com sucesso) e foi como esperado: 
https://github.com/edsoncelio/iac/runs/1935019310?check_suite_focus=true

**Comment by gomex** [comment]
Obrigado @edsoncelio
