### ISSUE TITLE
Ferramenta de log

### ISSUE THREAD

**Issue by gomex** [DadosAbertosDeFeira/iac#21]
Hoje o projeto usa logentries. Precisamos levantar o que precisa para criar uma conta fora do heroku e conectar a app pra enviar logo para o logentries: https://logentries.com/

**Comment by sergiocalmon** [comment]
Fala @gomex 

Pelo que entendi, é só habilitar o add-on do logentries  no heroku

https://elements.heroku.com/addons/logentries
https://devcenter.heroku.com/articles/logentries
https://docs.logentries.com/docs/heroku

**Comment by gomex** [comment]
@sergiocalmon na verdade precisamos disso fora do heroku.

**Comment by gomex** [comment]
Seria legal levantarmos outras opções, que podem ser melhores do que o Logentries.

As funcionalidades mais importantes em minha opinião são:

 - Preço (Ideal que seja de graça para projeto opensource ou com alguma limitação de armazenamento/retenção de logs)
 - Funcionalidades interessantes
 - Facilidade de configuração
 - Sem necessidade de subir nada novo na infra
 - Funcionalidade de tags para facilitar na busca

**Comment by Rafaelgomespinho** [comment]
Vou pesquisar @gomex.

**Comment by williamsanmartin** [comment]
Olá Pessoal,

A minha sugestão é utilizarmos o [LOGZ.IO](https://logz.io/)

Por que?

-  Existe uma conta free para a comunidade.
-  Tem uma documentação bem rica.
-  Há vários conectadores(Python, Go, Curl e etc..)
-  Dasboards e filtros avaçados integrados na solução.

**Comment by gomex** [comment]
Por hora usaremos o logentries até termos a nossa solução ;)
