### ISSUE TITLE
Colocar o deploy no Github actions

### ISSUE THREAD

**Issue by gomex** [DadosAbertosDeFeira/iac#3]
Pra começar, esse CI deve ter:

- [x] Execução do lint antes de qualquer coisa (Isso precisa ser introduzido aqui)
- [x] Execução molecule nesse repo IaC (com processo completo **molecule test**)
- [x] Execução do ansible-playbook no servidor VM que temos na Absam (pode colocar um endereço fake por hora, eu corrijo)

Sugestão de leitura: https://docs.github.com/pt/free-pro-team@latest/actions

**Comment by edsoncelio** [comment]
@gomex pode me atribuir essa issue? vou iniciar as atividades dela :D

**Comment by felipefrizzo** [comment]
@gomex como vc pensa em criar inventory ansible para executar o playbook no CI ? Eu não tenho nada em mente para essa parte

**Comment by gomex** [comment]
@edsoncelio vamos mantar o assign só pra quem vai revisar, que tal?

**Comment by gomex** [comment]
@felipefrizzo pensei em fazer  isso dinamicamente, dentro de um arquivo mesmo, construído pelo próprio CI a partir de uma variável no github actions ;)
