### ISSUE TITLE
Criar código pra manter bucket no AWS S3

### ISSUE THREAD

**Issue by gomex** [DadosAbertosDeFeira/iac#33]
Precisamos de um código para garantir que o bucket com um determinado nome exista, em uma determinada região.

A configuração deve permitir trocar as permissões do bucket, ao menos pra deixar público ou não. O padrão deve ser **NÃO** público.

Esse código deve ser testado no pipeline usando localstack ou algo equivalente.

Esse código deve ser um módulo a ser armazenado em repositório próprio: https://github.com/mentoriaiac/iac-modulo-s3

No repositório **iac** deve ter um arquivo terraform usado para consumir o módulo externo (que pode ser algo pronto ou feito por nós).

Esse modulo precisa ter ao menos um teste, que seria validar se o bucket se acessar via http, um bucket que não deveria ser público e validar se consegue upload de arquivos no bucket com a credencial correta.

Links que podem ajudar na solução do PR: 

https://github.com/localstack/localstack
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/custom-service-endpoints
https://github.com/UlisesGascon/sample-terraform-localstack
https://blog.gruntwork.io/how-to-create-reusable-infrastructure-with-terraform-modules-25526d65f73d

**Comment by imyrfeyj** [comment]
não tenho experiencia em terraform, mas tenho interesse em ajudar

**Comment by Riverfount** [comment]
Eu tenho interesse em fazer... vou iniciar aqui e assim que tiver algo eu faço um commit and push .... qq coisa marcamos uma call para trabalhar juntos @imyrfeyj e @gomex, blz?

**Comment by marcelomansur** [comment]
Também tenho interesse em participar, vou tentar começar algo por aqui. Pode me marcar na call? @Riverfount

**Comment by imyrfeyj** [comment]
> Eu tenho interesse em fazer... vou iniciar aqui e assim que tiver algo eu faço um commit and push .... qq coisa marcamos uma call para trabalhar juntos @imyrfeyj e @gomex, blz?

podemos sim, posso fazer a call qualquer dia depois da 18:30 ou fds

**Comment by GabrielSeiffert** [comment]
Vou embarcar com vocễs :)

**Comment by KarlCF** [comment]
Se ainda tiverem planejando a call, podem me chamar lá também.

**Comment by gomex** [comment]
PR draft do modulo: https://github.com/mentoriaiac/iac-modulo-s3/pull/1

**Comment by tainara-almeida** [comment]
Tenho interesse

**Comment by evandrobeserra** [comment]
Tenho interesse

**Comment by igufernando** [comment]
Tenho interesse.

**Comment by rodrigoabu1990** [comment]
Tenho interesse!!!
