### ISSUE TITLE
Criar infra de monitoramento

### ISSUE THREAD

**Issue by gomex** [DadosAbertosDeFeira/iac#4]
Monitoramentos iniciais:

- [ ] recursos da maquina
- [ ] webserver python
- [ ] RabbitMQ
- [ ] Tika
- [ ] Dramatiq

**Comment by bemanuel** [comment]
O que pretende utilizar?
 - Prometheus
 - FluentD

**Comment by gomex** [comment]
@bemanuel de cara Prometheus com certeza, agora o que fazer depois podemos ver nas próximas entregas.

**Comment by felipefrizzo** [comment]
O prometheus e outros serviços de monitoramento será hospedado na mesma máquina das apps ?

**Comment by gomex** [comment]
@felipefrizzo não necessariamente, mas não deveria fazer diferença na perspectiva do ansible ;)

**Comment by felipefrizzo** [comment]
@gomex você tem razão, pensando aqui, é melhor de qualquer jeito criar um hosts para deploy do ambiente de monitoramento

**Comment by gomex** [comment]
Pra começar, precisamos exporters para:

nginx
postgres
rabbitmq
Tika

**Comment by evandrobeserra** [comment]
Bom Dia Senhores!

Gostaria de ajudar no monitoramento da Infra. Tenho conhecimento em Zabbix e Grafana.

**Comment by gpxlnx** [comment]
Boa tarde pessoal. Tb trabalho com Zabbix, Promethues e tb ELK caso seja possível gostaria de participar.

**Comment by raitequi** [comment]
Galera, porque Prometheus seria a melhor opção?

**Comment by gomex** [comment]
@raitequi pq ele é melhor pra lidar com automação de infra. Devemos evitar ferramenta que precisa de configuração que seja feita via interface ou api e armazenada em banco de dados :(

**Comment by gomex** [comment]
Já está sendo tratado no projeto de observabilidade.
