### ISSUE TITLE
Criar modulo terraform pra controlar entradas no Cloudflare

### ISSUE THREAD

**Issue by gomex** [DadosAbertosDeFeira/iac#41]
Precisamos de um modulo terraform que eu possa passar um conjunto de entradas e o modulo ser responsável por criar no dominio escolhido.

exemplo de input:

```
rules = [
 {
   type = "A"
   entry = "@"
   value = "10.10.10.10"
 },
 {
   type = "cname"
   entry = "www"
   value = "@"
 }
  ]
 ```

**Comment by afonsoaugusto** [comment]
Para **Terraform** nós temos o provider da [Cloudflare](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs) 
Onde o registro é um [cloudflare_record](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/record)

O modulo tem que considerar diversos tipos de registros.
Segundo a documentação de [dns-records](https://www.cloudflare.com/pt-br/learning/dns/dns-records/), nós temos 24 tipos de registros, sendo 8 os mais comuns.

Sugiro que o modulo tenha suporte inicialmente para tipos simples (A, CNAME, NS),
depois para o tipo TXT, e por ultimo tipos complexos como SRV e LOC dentre os 8 principais.

Depois poderemos evoluir o modulo para todos os 24 tipos da documentação.

**Comment by afonsoaugusto** [comment]
Repositório para o modulo https://github.com/mentoriaiac/iac-modulo-cloudflare

**Comment by julialamenza** [comment]
Eu tenho interesse

**Comment by gomex** [comment]
Ja tem um PR como draft em andamento: https://github.com/mentoriaiac/iac-modulo-cloudflare/pull/1

**Comment by igufernando** [comment]
Tenho interesse. @afonsoaugusto

**Comment by igufernando** [comment]
Pessoal, criei o modulo básico mas funcional com entradas de Type: CNAME e A, está no meu fork no momento, gostaria de saber a forma correta de enviar pra voces avaliarem no repostiório principal.

**Comment by afonsoaugusto** [comment]
@ig

> Pessoal, criei o modulo básico mas funcional com entradas de Type: CNAME e A, está no meu fork no momento, gostaria de saber a forma correta de enviar pra voces avaliarem no repostiório principal.

Boa noite @igufernando , eu estou trabalhando em um fork para este modulo https://github.com/afonsoaugusto/iac-modulo-cloudflare/tree/terraform-cloudflare-record-module-issue-%2341
Podemos trabalhar nele em conjunto.
cc: @julialamenza @marcelomansur

**Comment by gomex** [comment]
https://github.com/mentoriaiac/iac-modulo-cloudflare
