### ISSUE TITLE
Fazer o nginx enviar log para o logentries

### ISSUE THREAD

**Issue by gomex** [DadosAbertosDeFeira/iac#48]
Não temos logs do nginx no logentries

**Comment by Rehzende** [comment]
Gostaria de saber mais sobre essa issue.

**Comment by gomex** [comment]
@Rehzende hoje o nginx não está mandando log para o logentries. Isso é pq ele está instalado na maquina e não roda em container. Precisamos criar um mecanismo para pegar o log do nginx e enviar para o logentries.

**Comment by gomex** [comment]
Essa issue não é mais necessária, pois a issue #56 é mais abrangente ;)
