### ISSUE TITLE
Hardening SSH

### ISSUE THREAD

**Issue by gomex** [DadosAbertosDeFeira/iac#49]
Precisamos reforçar a segurança fazendo hardening na configuração do SSH. Isso deve entrar na role: https://github.com/DadosAbertosDeFeira/iac-role-basica.

O escopo mínimo de hardening é:

- [ ] Não permitir login de root
- [ ] Login APENAS com chave publica
- [ ] Limitar o tempo de autenticação (LoginGraceTime)
- [ ] Limitar em 3 o número de tentativas
- [ ] Desabilitar outros métodos de autenticação ( ChallengeResponseAuthentication no, KerberosAuthentication no, GSSAPIAuthentication no)
- [ ] Desabilitar o X11Forwarding
- [ ] Desabilitar PermitUserEnvironment
- [ ] Desabilitar AllowAgentForwarding
- [ ] Desabilitar AllowTcpForwarding
- [ ] Desabilitar o PermitTunnel
- [ ] Desabilitar o Banner (DebianBanner?)
- [ ] Forçar o protocolo 2 (Protocol 2)

Você pode sugerir mais, porém esse apresentado até aqui é o mínimo que deve ser aplicado ^

Seria muito bom ter um teste automatizado pra validar algumas coisas dessa role no molecule também.

Obs: fail2ban está fora desse escopo. Seria MUITO legal ter isso, mas façamos em outro ticket.

Links: 

https://linux-audit.com/audit-and-harden-your-ssh-configuration/
https://www.digitalocean.com/community/tutorials/how-to-harden-openssh-on-ubuntu-18-04-pt

**Comment by mmagalha** [comment]
Gomex,

estou interessado nesse processo

**Comment by glenonmateus** [comment]
Bom dia,

gostaria de participar dessa issue

**Comment by apavanello** [comment]
Não seria interessante também incluir a autenticação em 2 fatores, o SSH já possui suporte a isso e pode ser utilizado em conjunto com o APP google authenticator (https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=pt_BR&gl=US) 

Seguem 2 links para apoio:

Artigo da própria Ubuntu sobre a configuração (em inglês) 
=> https://ubuntu.com/tutorials/configure-ssh-2fa#1-overview

Artigo em português (não oficial da Ubunutu)
=> https://blog.lsantos.dev/aplicando-two-factor-authentication-no-ssh/

**Comment by gomex** [comment]
Otima ideia @apavanello ! Podemos abrir um ticket novo só pra isso, pois muda bastante as coisa ;) Que tal?
