### ISSUE TITLE
Limitar o uso do worker no Mariaquiteria

### ISSUE THREAD

**Issue by gomex** [DadosAbertosDeFeira/iac#5]
Hoje ele consume muito recurso e inviabiliza a maquina. Precisamos avaliar o quanto de recurso é necessário e limitar pra evitar que a maquina seja  "tomada".

**Comment by bemanuel** [comment]
Bom dia, então não seria o caso dessa issue ter como dependência a Issue #4 ?

> Hoje ele consume muito recurso e inviabiliza a maquina. Precisamos avaliar o quanto de recurso é necessário e limitar pra evitar que a maquina seja "tomada".

**Comment by gomex** [comment]
> Bom dia, então não seria o caso dessa issue ter como dependência a Issue #4 ?
> 

Concordo contigo ;)

**Comment by gomex** [comment]
@bemanuel na verdade isso aqui seria pra usar o limits do docker no worker. Precisamos ver como fazer isso no dokku

**Comment by evandrobeserra** [comment]
Tenho interesse

**Comment by KarlCF** [comment]
Tenho interesse

**Comment by KarlCF** [comment]
Tenho interesse

**Comment by edsoncelio** [comment]
Pra galera que tem interesse em trabalhar nessa atividade, algumas dicas:
* O Dokku tem uma forma de limitar os recursos por app e por processo: https://github.com/dokku/dokku/blob/master/docs/advanced-usage/resource-management.md
* Na [role do Ansible](https://github.com/dokku/ansible-dokku) ainda não tem como usar isso, uma opção seria abrir um PR adicionando uma task pra isso, que permitisse fazer algo do tipo:
```
dokku resource:limit --cpu 100 --memory 100 --process-type worker my-awesome-app

```

**Comment by apavanello** [comment]
criado uma issue (https://github.com/dokku/ansible-dokku/issues/103)  e PR (https://github.com/dokku/ansible-dokku/pull/104) no repo do dokku-ansible  com os modulos para configurar as reservas e os limites.
Se aprovarem sem muitas modificações poderíamos implementar da seguinte maneira 

No dokku CLI:
- `dokku resource:limit --cpu 100 --memory 100 --process-type worker my-awesome-app`

Nos novo modulo de limite:
```yaml
- name: Criar limite para APP
  dokku_resource_limit:
    app: my-awesome-app
    process-type: worker
    resources:
      cpu: 100
      memory: 100
```

Agora é aguardar se vão gerar a PR

**Comment by apavanello** [comment]
Bom dia,
Nosso PR mergeado no repo do dokku-ansible, ja podemos atualizar com a nova release que já possui as opções de limite de recurso e com isso podemos dar continuidade nessa issue.
nova release:
https://github.com/dokku/ansible-dokku/releases/tag/v2021.5.8

**Comment by gomex** [comment]
SENSACIONAL @apavanello  ;)

**Comment by gomex** [comment]
Agora precisamos mudar o nosso requirements para essa nova versão e passar a usar essa nova funcionalidade:


No arquivo requirements.yml a mudança segue abaixo.

Mudar de:

```
- src: dokku_bot.ansible_dokku
  version: v2020.11.25
```

Para:

```
- src: dokku_bot.ansible_dokku
  version: v2021.5.8
```

Precisa implementar isso também no playbook.yml.

**Comment by apavanello** [comment]
Boa Tarde,

Estou retornado para essa issue, no caso temos os reserves e limits que podemos utilizar para o worker?
Se não tivermos, podemos nos basear no consumo médio e adicionar uns +20% para reserve e +100% para limits.

at

**Comment by gomex** [comment]
Vamos focar no k8s, sendo assim não vale a pena investir tempo nisso ;) <3 Obrigado todo esforço que fizemos até o momento. Ele contribuiu MUITO com a comunidade.
