### ISSUE TITLE
O playbook deve deployar um env por vez

### ISSUE THREAD

**Issue by gomex** [DadosAbertosDeFeira/iac#52]
Precisamos adaptar o playbook, pois o CI precisa de um comando pra fazer deploy APENAS em staging ou em produção por vez, para que staging possa ser testado antes de produção.

**Comment by klebercabral** [comment]
@gomex e @somatorio tenho interesse em contribuir para issue

**Comment by edsoncelio** [comment]
@gomex acho que podemos fechar essa issue :)

**Comment by gomex** [comment]
Valeu @edsoncelio
