### ISSUE TITLE
Erro ao instalar ansible usando venv (pelas instruções do README.md)

### ISSUE THREAD

**Issue by mariarsilva** [DadosAbertosDeFeira/iac#64]
Pessoal, ao tentar instalar o ansible pelas instruções do README.md, estou obtendo o seguinte erro:

> ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

Agradeço a atenção.

**Comment by claudiospj** [comment]
Quando você tenta o comando "pip install -r requirements.txt" o arquivo requirements.txt está no diretório corrento do bash? Acho que você pode tentar informar o caminho completo do arquivo requirements.txt também.

**Comment by mariarsilva** [comment]
> Quando você tenta o comando "pip install -r requirements.txt" o arquivo requirements.txt está no diretório corrento do bash? Acho que você pode tentar informar o caminho completo do arquivo requirements.txt também.

Sim, ao informar o caminho completo consegui instalar, muito obrigada!
