### ISSUE TITLE
Mudança de tasks por post_tasks

### ISSUE THREAD

**Issue by corsas** [DadosAbertosDeFeira/iac#68]
Olá, acredito que no arquivo playbook.yml ficaria mais intuitivo e idiomático se fosse trocado `tasks` por `post_tasks` , pois penso que a primeira vista pode ser confundido a ordem de execução entre `tasks ` e  `roles`.

**Comment by gomex** [comment]
Obrigado pela sugestão, mas vamos migrar esse deploy para ECS e vamos depreciar esse playbook.
