### ISSUE TITLE
Role para configurar o Let's Encrypt

### ISSUE THREAD

**Issue by francilioaraujo** [DadosAbertosDeFeira/iac#7]
Replicar o que é feito pelo [plugin dokku-letsencrypt](https://github.com/dokku/dokku-letsencrypt) em um role ansible.

Os passos são documentados [neste artigo](https://blog.semicolonsoftware.de/securing-dokku-with-lets-encrypt-tls-certificates/) e podem ser complementados pelos scripts que compoem o plugin no github.

Esta atividade faz parte do issue #1

**Comment by gomex** [comment]
Segue o repo que deve ser usado: https://github.com/DadosAbertosDeFeira/iac-dokku-lets-encrypt

**Comment by gomex** [comment]
Não precisamos dessa role por hora. O Provedor prover isso.
